# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MarvelXP' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MarvelXP

  target 'MarvelXPTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MarvelXPUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
