# Uncomment the next line to define a global platform for your project
platform :ios, '12.2'

use_frameworks!

def shared_pods
  pod 'Alamofire', '~> 4.7'
  pod 'CryptoSwift'
end

def test_pods
  pod 'Quick', '~> 1.3.2'
  pod 'Nimble', '~> 7.3.2'
end

target 'ChallengeMarvel' do
  inherit! :search_paths
  shared_pods
end

target 'ChallengeMarvelTests' do
  inherit! :search_paths
  shared_pods
  test_pods
end

target 'ChallengeMarvelUITests' do
  inherit! :search_paths
  shared_pods
end

target 'ChallengeMarvelWidget' do
  inherit! :search_paths
  shared_pods
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = ‘4.2’
      config.build_settings['ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES'] = 'YES'
    end
  end
end
